version: '3.7'

services:
  tourguide:
    image: tourguide:1.0.0
    depends_on:
      - tourguidetrippricer
      - tourguidegps
      - tourguidereward
    ports:
      - "8088:8088"
    networks:
      - backend

  tourguidetrippricer:
    image: trippricer:1.0.0
    ports:
      - "8084:8084"
    networks:
      - backend

  tourguidegps:
    image: tourguidegps:1.0.0
    ports:
      - "8082:8082"
    networks:
      - backend

  tourguidereward:
    image: rewardcentral:1.0.0
    ports:
      - "8083:8083"
    networks:
      - backend

networks:
  backend:
    driver: "host"